osx_image: xcode7.2
language: objective-c

branches:
  only:
    - master
    - develop

before_install:
 - ./scripts/before_install

install:
 - ./scripts/bootstrap

env:
 - workspace="Example/StylingKit.xcworkspace" scheme="StylingKit-Example" destination="platform=iOS Simulator,name=iPhone 6s"

script:
 - ./scripts/travis_build
