osx_image: xcode8.3 # update destination iOS when upgrade
language: objective-c

rvm: 2.2

branches:
  only:
    - master
    - develop

before_install:
  - sysctl -n machdep.cpu.brand_string
  - sysctl hw

install:
  - ./scripts/bootstrap

env:
  global:
    - workspace="Example/StylingKit.xcworkspace"
    - scheme="StylingKit-Example"
    - destination="platform=iOS Simulator,name=iPhone 6s,OS=10.1"

  matrix:
    - CURRENT_STAGE=0
    - CURRENT_STAGE=1
    - CURRENT_STAGE=2

script:
  - ./scripts/travis_build.${CURRENT_STAGE}

