osx_image: xcode7.2
language: objective-c

branches:
  only:
    - master
    - develop

env:
 - workspace="Example/StylingKit.xcworkspace"
 - scheme="StylingKit-Example"

script:
- open -b com.apple.iphonesimulator #start simulator in advance as xcodebuild sometimes fails to do so
- set -o pipefail && xcodebuild clean build -workspace env.workspace -scheme env.scheme ONLY_ACTIVE_ARCH=NO | xcpretty
- set -o pipefail && xcodebuild test -workspace env.workspace -scheme env.scheme -destination "platform=iOS Simulator,name=iPhone 6s" | xcpretty
- pod lib lint
