osx_image: xcode7.2
language: objective-c

script:
- set -o pipefail && xcodebuild test -workspace Example/StylingKit.xcworkspace -scheme StylingKit-Example -destination "platform=iOS Simulator,name=iPhone 6s" ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
